a:
	gcc -o lab07_gabinete_A.elf lab07_gabinete_A.c
	./lab07_gabinete_A.elf
b:
	gcc -o lab07_gabinete_B.elf lab07_gabinete_B.c
	./lab07_gabinete_B.elf
	
read:
	gcc -o readingInput sampleReading.c
	./readingInput

clean:
	rm -f *.elf