run:
	gcc -o lab08_gabinete.elf lab08_gabinete.c -pthread
	./lab08_gabinete.elf

read:
	gcc -o fileReading.elf fileReading.c -pthread
	./fileReading.elf


sample:
	gcc -o sample2 sample2.c -pthread
	./sample2
